/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  books: [
    // 'books/intro',
    {
      type: 'autogenerated',
      dirName: 'books', // Generate sidebar slice from docs/tutorials/easy
    },

    // {
    //   type: 'category',
    //   label: '책1',
    //   items: [
    //     // 'intro',
    //     {
    //       type: 'autogenerated',
    //       dirName: 'books/book1', // Generate sidebar slice from docs/tutorials/easy
    //     },
    //     {
    //       type: 'autogenerated',
    //       dirName: 'books/book2', // Generate sidebar slice from docs/tutorials/easy
    //     },
    //   ],
    // },
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
